CREATE DATABASE homeland
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

use homeland;

DROP TABLE IF EXISTS Category;
CREATE TABLE Category
(
	CategoryID INT NOT NULL AUTO_INCREMENT,
	ParentID INT,
	CatName VARCHAR(255) NOT NULL,
	Url VARCHAR(255),
	Active int(1) NOT NULL default 1,
  Crawled int(1) NOT NULL default 0,

	PRIMARY KEY(CategoryID),
	INDEX (ParentID),
	FOREIGN KEY(ParentID) REFERENCES Category(CategoryID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

insert into Category(CatName, Url, Active) VALUE ('Nhà đất bán', 'https://batdongsan.com.vn/nha-dat-ban', 1);

DROP TABLE IF EXISTS City;
CREATE TABLE City
(
	CityID INT NOT NULL AUTO_INCREMENT,
	CityName VARCHAR(255) NOT NULL,
	Longitude FLOAT,
	Latitude FLOAT,

	PRIMARY KEY(CityID),
	INDEX (CityName)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS District;
CREATE TABLE District
(
	DistrictID INT NOT NULL AUTO_INCREMENT,
	CityID INT NOT NULL,
	DistrictName VARCHAR(255) NOT NULL,
	Longitude FLOAT,
	Latitude FLOAT,

	PRIMARY KEY(DistrictID),
	INDEX (DistrictName),
	FOREIGN KEY(CityID) REFERENCES City(CityID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS Ward;
CREATE TABLE Ward
(
	WardID INT NOT NULL AUTO_INCREMENT,
	DistrictID INT NOT NULL,
	WardName VARCHAR(255) NOT NULL,
	Longitude FLOAT,
	Latitude FLOAT,

	PRIMARY KEY(WardID),
	INDEX (WardName),
	FOREIGN KEY(DistrictID) REFERENCES District(DistrictID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS Street;
CREATE TABLE Street
(
	StreetID INT NOT NULL AUTO_INCREMENT,
	WardID INT NOT NULL,
	StreetName VARCHAR(255) NOT NULL,
	Longitude FLOAT,
	Latitude FLOAT,

	PRIMARY KEY(StreetID),
	INDEX (StreetName),
	FOREIGN KEY(WardID) REFERENCES Ward(WardID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


DROP TABLE IF EXISTS Brand;
CREATE TABLE Brand
(
	BrandID INT NOT NULL AUTO_INCREMENT,
	BrandName VARCHAR(255) NOT NULL,
	Description TEXT,

	PRIMARY KEY(BrandID),
	INDEX (BrandName)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table brand add column Source VARCHAR(255);

DROP TABLE IF EXISTS Direction;
CREATE TABLE Direction
(
	DirectionID INT NOT NULL AUTO_INCREMENT,
	DirectionName VARCHAR(255) NOT NULL,

	PRIMARY KEY(DirectionID),
	INDEX (DirectionName)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS Product;
CREATE TABLE Product
(
	ProductID INT NOT NULL AUTO_INCREMENT,
	Code VARCHAR(20) NOT NULL,
	Title VARCHAR(512) NOT NULL,
	Brief VARCHAR(1024) NOT NULL,
	Href VARCHAR(255),
	Price FLOAT,
	PriceString VARCHAR(125),
	Area VARCHAR(50),
	Detail TEXT,
	Thumb VARCHAR(255),
	Address VARCHAR(255),
	Floor VARCHAR(20),
	Room VARCHAR(20),
	WidthSize VARCHAR(20),
	LongSize VARCHAR(20),
	Toilet VARCHAR(20),
	Longitude FLOAT,
  Latitude FLOAT,
  ContactName VARCHAR(125),
  ContactPhone VARCHAR(125),
  ContactAddress VARCHAR(512),
  ContactMobile VARCHAR(125),
  ContactEmail VARCHAR(50),
  ExpireDate TIMESTAMP,
	PostDate TIMESTAMP NOT NULL,
  DirectionID INT,
  BrandID INT,
  CityID INT,
  DistrictID INT,
  WardID INT,
  Street VARCHAR(255),
  CategoryID INT NOT NULL,
  Status INT, -- 1: active, 0: disable
  View INT,
  Source VARCHAR(125),
  ModifiedDate TIMESTAMP,
  CreatedByID INT,
  UnitID INT,


	PRIMARY KEY(ProductID),
	INDEX (Code),
	FOREIGN KEY(DirectionID) REFERENCES Direction(DirectionID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(BrandID) REFERENCES Brand(BrandID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(CityID) REFERENCES City(CityID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(DistrictID) REFERENCES District(DistrictID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(WardID) REFERENCES Ward(WardID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS ProductAsset;
CREATE TABLE ProductAsset
(
	ProductAssetID INT NOT NULL AUTO_INCREMENT,
	ProductID INT NOT NULL,
	Url VARCHAR(255) NOT NULL,
	OrgUrl VARCHAR(255),

	PRIMARY KEY(ProductAssetID),
	INDEX (ProductID),
	FOREIGN KEY(ProductID) REFERENCES Product(ProductID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS CrawlerHistory;
CREATE TABLE CrawlerHistory
(
	CrawlerHistoryID INT NOT NULL AUTO_INCREMENT,
	CategoryID INT NOT NULL,
	Added INTEGER(5),
	Updated INTEGER(5),
	Error INTEGER(5),
	UpdatedDate TIMESTAMP NOT NULL,

	PRIMARY KEY(CrawlerHistoryID),
	FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS UserGroup;
CREATE TABLE UserGroup
(
	UserGroupID INT NOT NULL AUTO_INCREMENT,
	Code VARCHAR(125) NOT NULL,
	GroupName VARCHAR(255) NOT NULL,

	PRIMARY KEY(UserGroupID)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS Us3r;
CREATE TABLE Us3r
(
	Us3rID INT NOT NULL AUTO_INCREMENT,
	UserGroupID INT NOT NULL,
	UserName VARCHAR(125) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	Email VARCHAR(50),
	Phone VARCHAR(20) NOT NULL,
	RequestPassword BOOLEAN NOT NULL DEFAULT false,
	CreatedDate TIMESTAMP NOT NULL,
	UpdatedDate TIMESTAMP NOT NULL,

	PRIMARY KEY(Us3rID),
	FOREIGN KEY(UserGroupID) REFERENCES UserGroup(UserGroupID) ON UPDATE CASCADE ON DELETE RESTRICT
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS Role;
CREATE TABLE Role
(
	RoleID INT NOT NULL AUTO_INCREMENT,
	Code VARCHAR(125) NOT NULL,
	Name VARCHAR(255) NOT NULL,

	PRIMARY KEY(RoleID)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

